import type { Copy } from './types';

export function copy(value: Copy, language: string): string {
  return language === 'fr' ? value.fr : value.en;
}
const labels: Record<string, Copy> = {
  name: { en: 'Name', fr: 'Nom' },
  slug: { en: 'Short name', fr: 'Nom court' },
  status: { en: 'Status', fr: 'Statut' },
  type: { en: 'Type', fr: 'Type' },
  organizationId: { en: 'Organization', fr: 'Organisation' },
  parentOrganizationId: { en: 'Parent organization', fr: 'Organisation parente' },
  childOrganizationId: { en: 'Child organization', fr: 'Organisation rattachée' },
  teamId: { en: 'Team', fr: 'Équipe' },
  membershipId: { en: 'Member', fr: 'Membre' },
  managerMembershipId: { en: 'Manager', fr: 'Responsable' },
  ownerId: { en: 'Owner', fr: 'Responsable' },
  assignedUserId: { en: 'Assignee', fr: 'Personne affectée' },
  campaignId: { en: 'Campaign', fr: 'Campagne' },
  territoryId: { en: 'Territory', fr: 'Territoire' },
  parentId: { en: 'Parent territory', fr: 'Territoire parent' },
  regionId: { en: 'Region', fr: 'Région' },
  parentRegionId: { en: 'Parent region', fr: 'Région parente' },
  capacity: { en: 'Capacity', fr: 'Capacité' },
  target: { en: 'Target', fr: 'Objectif' },
  metric: { en: 'Metric', fr: 'Indicateur' },
  startsAt: { en: 'Start date & time', fr: 'Date et heure de début' },
  endsAt: { en: 'End date & time', fr: 'Date et heure de fin' },
  nextRunAt: { en: 'Next run', fr: 'Prochaine exécution' },
  expiresAt: { en: 'Expires', fr: 'Expiration' },
  createdAt: { en: 'Created', fr: 'Création' },
  updatedAt: { en: 'Updated', fr: 'Modification' },
  completedAt: { en: 'Completed', fr: 'Achèvement' },
  displayName: { en: 'Name', fr: 'Nom' },
  email: { en: 'Email', fr: 'E-mail' },
  description: { en: 'Description', fr: 'Description' },
  reason: { en: 'Reason', fr: 'Motif' },
  locale: { en: 'Language', fr: 'Langue' },
  timezone: { en: 'Timezone', fr: 'Fuseau horaire' },
  requireMfa: {
    en: 'Require multi-factor authentication',
    fr: 'Exiger l’authentification multifacteur',
  },
  passwordMinLength: { en: 'Minimum password length', fr: 'Longueur minimale du mot de passe' },
  sessionMaxHours: { en: 'Maximum session hours', fr: 'Durée maximale de session (heures)' },
  clientSecret: { en: 'Client secret', fr: 'Secret client' },
  clientId: { en: 'Client identifier', fr: 'Identifiant client' },
  issuer: { en: 'Issuer URL', fr: 'URL de l’émetteur' },
  allowedDomains: { en: 'Allowed domains', fr: 'Domaines autorisés' },
  reportKey: { en: 'Report', fr: 'Rapport' },
  reportType: { en: 'Report type', fr: 'Type de rapport' },
  cadence: { en: 'Frequency', fr: 'Fréquence' },
  format: { en: 'Format', fr: 'Format' },
  recipients: { en: 'Recipients', fr: 'Destinataires' },
  filters: { en: 'Filters', fr: 'Filtres' },
  fieldKey: { en: 'Field key', fr: 'Clé du champ' },
  label: { en: 'Label', fr: 'Libellé' },
  dataType: { en: 'Value type', fr: 'Type de valeur' },
  validation: { en: 'Validation', fr: 'Validation' },
  visibility: { en: 'Visibility', fr: 'Visibilité' },
  roles: { en: 'Roles', fr: 'Rôles' },
  role: { en: 'Role', fr: 'Rôle' },
  permissions: { en: 'Permissions', fr: 'Autorisations' },
  scopes: { en: 'Allowed permissions', fr: 'Autorisations accordées' },
  required: { en: 'Required', fr: 'Obligatoire' },
  options: { en: 'Choices', fr: 'Choix' },
  color: { en: 'Color', fr: 'Couleur' },
  resource: { en: 'Resource', fr: 'Ressource' },
  resourceType: { en: 'Resource type', fr: 'Type de ressource' },
  columns: { en: 'Columns', fr: 'Colonnes' },
  sort: { en: 'Sorting', fr: 'Tri' },
  shared: { en: 'Shared with workspace', fr: 'Partagée avec l’espace' },
  isDefault: { en: 'Default view', fr: 'Vue par défaut' },
  strategy: { en: 'Distribution strategy', fr: 'Stratégie de répartition' },
  priority: { en: 'Priority', fr: 'Priorité' },
  targets: { en: 'Eligible teams & members', fr: 'Équipes et membres éligibles' },
  requiredSkills: { en: 'Required skills', fr: 'Compétences requises' },
  maxDistanceKm: { en: 'Maximum distance (km)', fr: 'Distance maximale (km)' },
  resolution: { en: 'Resolution', fr: 'Résolution' },
  targetId: { en: 'Prospect to keep', fr: 'Prospect à conserver' },
  leftProspectId: { en: 'First prospect', fr: 'Premier prospect' },
  rightProspectId: { en: 'Second prospect', fr: 'Second prospect' },
  matchingKeys: { en: 'Matching information', fr: 'Informations correspondantes' },
  isActive: { en: 'Active', fr: 'Actif' },
  active: { en: 'Active', fr: 'Actif' },
  accessMode: { en: 'Participation', fr: 'Participation' },
  teamRole: { en: 'Team role', fr: 'Rôle dans l’équipe' },
  relationshipType: { en: 'Relationship', fr: 'Relation' },
  provider: { en: 'Provider', fr: 'Fournisseur' },
  config: { en: 'Configuration', fr: 'Configuration' },
  url: { en: 'Destination URL', fr: 'URL de destination' },
  events: { en: 'Events', fr: 'Événements' },
  action: { en: 'Action', fr: 'Action' },
  decision: { en: 'Decision', fr: 'Décision' },
  outcomes: { en: 'Outcomes', fr: 'Résultats' },
  code: { en: 'Code', fr: 'Code' },
  behavior: { en: 'Behavior', fr: 'Comportement' },
  enabled: { en: 'Enabled', fr: 'Activé' },
  actionTypes: { en: 'Action types', fr: 'Types d’action' },
  boundary: { en: 'Geographic boundary', fr: 'Limite géographique' },
  periodStart: { en: 'Period start', fr: 'Début de période' },
  periodEnd: { en: 'Period end', fr: 'Fin de période' },
  search: { en: 'Search', fr: 'Recherche' },
  state: { en: 'State', fr: 'État' },
  from: { en: 'From', fr: 'Du' },
  to: { en: 'To', fr: 'Au' },
  'progress.actual': { en: 'Achieved', fr: 'Réalisé' },
  'progress.status': { en: 'Progress', fr: 'Progression' },
};
export function fieldLabel(name: string, language: string): string {
  if (labels[name]) return copy(labels[name], language);
  const text = name.replace(/([a-z])([A-Z])/g, '$1 $2').replace(/[_.-]/g, ' ');
  return text.charAt(0).toUpperCase() + text.slice(1);
}
export function text(en: string, fr: string, language: string): string {
  return language === 'fr' ? fr : en;
}
